<div class="row text-center">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <ul class="tab-buttons">

                        <li class="selected5"><a href="<?=$this->url("enseignant/controller-action",array("controller"=>"create","action"=>"menu-cv-enseignant" ),null,true)?>" data-rel="item-three"><i class="fa fa-user"></i><span>Mon Compte</span></a></li>

                        <li class="selected1"><a href="<?=$this->url("enseignant/controller-action",array("controller"=>"mes-invitations","action"=>"lister-mes-invitations" ),null,true)?>" data-rel="item-three"><i class="fa fa-book"></i><span>Mes tutorat</span></a></li>

                        <li class="selected2"><a href="<?=$this->url("enseignant/controller-action",array("controller"=>"create","action"=>"menu-cv-enseignant" ),null,true)?>" data-rel="item-two"><i class="fa fa-files-o"></i><span>Edition des notes</span></a></li>

                    </ul></div><!--- END COL -->
            </div>
        </div>
    </div>
</div>