<?php
declare(strict_types = 1);
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<div class="row">
    <div class="col-md-8">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('Creation_Ens_Travail')?></h3>
            </div>
            <div class="box-body">
                    <form class="form-horizontal" role="form" action="" method="post">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label"><?=$this->translate('Ens_Trav_Type_Travail')?></label>

                            <div class="col-sm-8">
                                <select  class="form-control" id="typetrav">
                                        <option value=""><?=$this->translate('Select_ChoixVide_Type_Trav')?></option>
                                </select>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">

    </div>
</div>