<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<script type="text/javascript">
    $(function(){
        AjaxLoader('<?=$this->url("enseignant/controller-action",array("controller"=>"create","action"=>"liste-mes-grades-ens"),null,true)?>',1,'ListeContent')

        AjaxLoader('<?=$this->url("enseignant/controller-action",array("controller"=>"create","action"=>"mon-grade-ens"),null,true)?>',1,'FormContent')

    });
</script>

<div class="row">

    <div class="col-md-5" id="FormContent"></div>

    <div class="col-md-7" id="ListeContent"></div>
</div>