<?php
$flash=$this->flashMessenger()
    ->setMessageOpenFormat('<div%s>')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>');
?>
<?php
$this->headTitle("aaaa");
$form = $this->form;
$form->prepare();
$formLabel = $this->plugin('formLabel');
?>
<div class="row">

    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3><?=$this->translate("enseignants_title_create")?></h3>

            </div>
            <div class="box-body">
                <?php
                echo $this->form()->openTag($form);
                echo $flash->render('save_enseignants',array('btn', 'btn-danger'));
                ?>
                <div class="row">
                    <div class="col-md-12">
                        <fieldset>
                            <legend><?=$this->translate("enseignants_legende_Identiter")?></legend>
                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('societer');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>

                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('poste');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>

                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('fonction');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>


                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('daterecrutement');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formDate($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>
                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('datefin');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formDate($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>

                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('descposte');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formTextarea($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>

                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('adresspro');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formTextarea($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>

                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('codepostal');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>
                            <div class="form-group">
                                <?php
                                $eltForm = $form->get('telephonepro');
                                echo $formLabel->openTag(). $this->translate($eltForm->getOption('label')) ." ";
                                echo $this->formInput($eltForm);
                                echo $this->formElementErrors($eltForm);
                                echo $formLabel->closeTag();
                                ?>
                            </div>



                        </fieldset>

                    </div>

                </div>


                <?php
                echo $this->form()->closeTag();
                echo $this->formElement($form->get('save_InfoProEns'));
                ?>
            </div>
        </div>
    </div>
</div>



