<?php

//print_r($this->form);die();
//print_r($this->rows->toArray());die();
$diplomeactive="";
$formationactive="59";
$this->rowssem->buffer();
?>

<script type="text/javascript">
    $(function(){


        var optmyform = {
            beforeSend: function()  { },
            uploadProgress: function(event, position, total, percentComplete) { },
            success: function() { },
            complete: function(response)
            {
                var obj = JSON.parse(response.responseText);
                if(obj.status=="success"){
                    $("#messageconfig").html("<div class='alert alert-success'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'>Success d'insertion des données</h4>"
                        +"<p> "+obj.status
                        +" </p> </div>");
                    treeconstractor();

                }else{

                    $("#messageconfig").html("<div class='alert alert-block alert-error fade in'>"
                        +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                        +"<h4 class='alert-heading'>Erreur d'insertion des données</h4>"
                        +"<p> "+obj.message
                        +" </p> </div>");


                }

            },
            error: function(response)
            {
                var obj = JSON.parse(response.responseText);
                $("#messageconfig").html("<div class='alert alert-block alert-error fade in'>"
                    +"<button type='button' class='close' data-dismiss='alert'>X</button>"
                    +"<h4 class='alert-heading'>Erreur d'insertion des données</h4>"
                    +"<p> "+obj.message
                    +" </p> </div>");

            }

        };
        $("#sendinvite").ajaxForm(optmyform);


        /****************Chargement de la liste des diplome**********************/
        var url="<?=$this->url('pedagogie/controller-action',array('controller'=>'dashboard','action' =>'infogenform'), null, true); ?>";
        $.ajax({
            type:"POST",
            url:"<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action' =>'getdiplomesoption'), null, true); ?>",

            beforeSend :function(){$('#diplomeecue').html("<option>Encours... </option>");},
            success:function(response){

                $("#diplomeecue").html(response);
                $("#diplomeecue").val("<?=$diplomeactive?>");
                $('#diplomeecue').trigger("chosen:updated");

                $.ajax({
                    type:"POST",
                    url:"<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action' =>'getformationoption'), null, true); ?>",
                    data:{idpere:'<?=$diplomeactive?>'},
                    beforeSend :function(){$('#formationecue').html("<option>Encours... </option>");},
                    success:function(response){

                        $("#formationecue").html(response);
                        $("#formationecue").val("<?=$formationactive?>");
                        $('#formationecue').trigger("chosen:updated");

                    }
                });
            }
        });




    }) ;






</script>
<?php
$flash=$this->flashMessenger()
    ->setMessageOpenFormat('<div%s>')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>');
?>
<?php
$this->headTitle("aaaa");
$form = $this->form;
$form->setAttribute('action', $this->url("enseignant/controller-action",array("controller"=>"create","action"=>"inviter-coordinateur-mail-send",'id'=>$this->idformation),null,true));

$form->prepare();
$formLabel = $this->plugin('formLabel');
?>
<div id="messageconfig"></div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><i class="fa fa-book text-aqua"></i> <?=$this->translate('details_formation')?></h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>

            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-7">
                        <table class="table">
                            <thead>
                            <?php foreach($this->formation as $f):?>
                                <tr>
                                    <th><?=$f['idtypeformation']?></th>
                                    <td><?=$f['Label']?></td>
                                </tr>
                            <?php endforeach;?>
                            </thead>

                        </table>
                    </div>
                    <div class="col-md-5">
                        <div class="box">
                            <div class="box-header">
                                <?=$this->translate('description_formation')?>
                            </div>
                            <div class="box-body">

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
 
    <div class="row">
        <div class="col-md-7">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title text-aqua"><i class="fa fa-mortar-board "></i>
                         <?=$this->translate("enseignants_title_inviter_coordinateur",null,$this->langue)?></h3>

                    </h3>
                </div>
                <div class="box-body">
                    <?php
                    echo $this->form()->openTag($form);
                    echo $flash->render('save_inviteCorrdinateur',array('btn', 'btn-danger'));
                    ?>
                    <div class="form-group">
                        <?php
                        $eltform = $form->get('anneescolaire');
                        echo $formLabel->openTag(). $this->translate($eltform->getOption('label'),null,$this->langue) ." ";
                        echo $this->formSelect($eltform);
                        echo $this->formElementErrors($eltform);
                        echo $formLabel->closeTag();
                        ?>
                    </div>

                    <div class="form-group">
                        <?php
                        $eltform = $form->get('email');
                        echo $formLabel->openTag(). $this->translate($eltform->getOption('label'),null,$this->langue) ." ";
                        echo $this->formEmail($eltform);
                        echo $this->formElementErrors($eltform);
                        echo $formLabel->closeTag();
                        ?>
                    </div>

                    <div class="form-group">
                        <?php
                        $eltform = $form->get('nom');
                        echo $formLabel->openTag(). $this->translate($eltform->getOption('label'),null,$this->langue) ." ";
                        echo $this->formInput($eltform);
                        echo $this->formElementErrors($eltform);
                        echo $formLabel->closeTag();
                        ?>
                    </div>

                    <div class="form-group">
                        <?php
                        $eltform = $form->get('prenom');
                        echo $formLabel->openTag(). $this->translate($eltform->getOption('label'),null,$this->langue) ." ";
                        echo $this->formInput($eltform);
                        echo $this->formElementErrors($eltform);
                        echo $formLabel->closeTag();
                        ?>
                    </div>


                    <?php

                    echo $this->formElement($form->get('submit'));
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="box">
                <div class="box-header"></div>
                <div class="box-body">
                    L'invitation sera envoyé au coordinateur afin qu'il saisie son cv
                </div>
            </div>
        </div>
    </div>


 



