<script type="text/javascript">
    $(function(){
        $('#EnseignantsForm').validationEngine('attach', {focusFirstField : false});
    });
</script>

<?php
$flash=$this->flashMessenger()
    ->setMessageOpenFormat('<div%s>')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>');
?>
<?php
$this->headTitle("Creation de compte");
$form = $this->form;
$form->setAttribute('action', $this->url("enseignant/controller-action",array("controller"=>"mon-compte","action"=>"save-compte"),array('query'=>array("idInvite"=>$this->idinvite)),true));

$form->prepare();
$formLabel = $this->plugin('formLabel');
?>
<div class="row">

    <div class="col-md-12" <?=$this->langue=="ar_AR" ? "dir='rtl'" : '' ?>>
        <div class="box">

            <div class="box-body">
                <?php
                echo $this->form()->openTag($form);
                echo $flash->render('save_diplomeens',array('btn', 'btn-danger'));
                ?>

                <div class="row">
                    <div class="col-md-6">
                        <div class="box box-info">
                            <div class="box-header"></div>
                            <div class="box-body">
                                <fieldset>
                                    <legend></legend>
                                    <div class="row">

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <?php
                                                $elt = $form->get('cin');
                                                echo $formLabel->openTag(). $this->translate($elt->getOption('label'),null,$this->langue) ." ";
                                                echo $this->formInput($elt);
                                                echo $this->formElementErrors($elt);
                                                echo $formLabel->closeTag();
                                                ?>
                                            </div>
                                            <div class="form-group">
                                                <?php
                                                $elt = $form->get('nom');
                                                $elt->setValue($this->nom);
                                                echo $formLabel->openTag(). $this->translate($elt->getOption('label'),null,$this->langue) ." ";
                                                echo $this->formInput($elt);
                                                echo $this->formElementErrors($elt);
                                                echo $formLabel->closeTag();
                                                ?>
                                            </div>
                                            <div class="form-group">
                                                <?php
                                                $elt = $form->get('prenom');
                                                echo $formLabel->openTag(). $this->translate($elt->getOption('label'),null,$this->langue) ." ";
                                                $elt->setValue($this->prenom);
                                                echo $this->formInput($elt);
                                                echo $this->formElementErrors($elt);
                                                echo $formLabel->closeTag();
                                                ?>
                                            </div>

                                            <div class="form-group">
                                                <?php
                                                $elt = $form->get('email');
                                                $elt->setValue($this->email);
                                                echo $formLabel->openTag(). $this->translate($elt->getOption('label'),null,$this->langue) ." ";
                                                echo $this->formEmail($elt);
                                                echo $this->formElementErrors($elt);
                                                echo $formLabel->closeTag();
                                                ?>
                                            </div>
                                            <div class="form-group">
                                                <?php
                                                $elt = $form->get('motdepass');
                                                echo $formLabel->openTag(). $this->translate($elt->getOption('label'),null,$this->langue) ." ";
                                                echo $this->formPassword($elt);
                                                echo $this->formElementErrors($elt);
                                                echo $formLabel->closeTag();
                                                ?>
                                            </div>


                                            <div class="form-group">
                                                <?php
                                                $elt = $form->get('confirmmotdepass');
                                                echo $formLabel->openTag(). $this->translate($elt->getOption('label'),null,$this->langue) ." ";
                                                echo $this->formPassword($elt);
                                                echo $this->formElementErrors($elt);
                                                echo $formLabel->closeTag();
                                                ?>
                                            </div>

                                        </div>
                                    </div>


                                </fieldset>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box box-info">
                            <div class="box-header">

                            </div>
                            <div class="box-body">
                                <section>
                                    <h3>Importance de la sécurité</h3>
                                    <article>
                                        <h4>Les informations de compte sont personnel</h4>
                                        <p>
                                        </p>
                                    </article>

                                    <article>
                                        <h4>Changement de mot de passe</h4>
                                        <p>
                                            Il faut changer votre mot de passe d'une faon cyclique pour....
                                        </p>
                                    </article>
                                    <article>
                                        <h4>Oublier son mot de passe</h4>
                                        <p>
                                        </p>
                                    </article>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>


                <?php

                echo $this->formElement($form->get('save_compte'));
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>



