<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<div class="box">
    <div class="box-header"></div>
    <div class="box-body">
        <section>
            <h3 class="text-blue">Aide de saisie des informations</h3>
            <article>
                <h4 class="text-red">Information Administrative <?=$this->translate("Menu_CV_Titre_InfoGenerale",null,"ar_AR")?></h4>
                <p>
                    Les informations demander dans cette rebrique permet
                    de générer le document administrative qui sera signez par vous et déposer chez le service
                    affaire pédagogique afin de completer l'ensemble de vos documents
                </p>
            </article>
            <hr>
            <article>
                <h4 class="text-green">Information de CV, Profissionnel et activité </h4>
                <p>
                    chaque information va nous permettre de vous guidez, vous informer et vous donnée plus de details
                    sur l'activité de l'UVT afin de mener de bien votre mission de tutorat


                </p>
            </article>
        </section>
    </div>

</div>