<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header"></div>
            <div class="box-body">
                <table class="table  table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Document</th>
                            <th>Obligatoire</th>
                            <th>Date depôt</th>
                            <th><i class="fa fa-download"></i> / <i class="fa  fa-upload"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->doctype as $doctype):?>
                            <tr>
                                <td><?=$doctype->titredoc?></td>
                                <td><?=$doctype->docobligatoire?></td>
                                <td> </td>
                                <td><i class="fa fa-download"></i> / <input type="file" class="form-control" value="Télécharger"> <i class="fa  fa-upload"></i></td>
                            </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>