<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<div class="box">
    <div class="box-body">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th><?=$this->translate('diplomeens_label_titrediplome',null,$this->langue)?></th>
                <th><?=$this->translate('diplomeens_label_specialiterdiplome',null,$this->langue)?></th>
                <th><?=$this->translate('diplomeens_label_etablissement',null,$this->langue)?></th>
                <th><?=$this->translate('diplomeens_label_pays',null,$this->langue)?></th>
            </tr>
            </thead>
            <tbody>

            </tbody>
            <tfoot>

            </tfoot>
        </table>
    </div>
</div>