<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<?php
//$this->h1('pedagogie_title_create');

//$this->formationsDataForm->setAttribute('action', $this->url('pedagogie/create'));

 ///echo $this->bootstrapForm($this->form);
?>
<p>
    <a class="btn btn-primary" href="<?php echo $this->url('pedagogie'); ?>">
        <i class="fa fa-table"></i>
        <?php echo $this->translate('pedagogie_action_index'); ?>
    </a>
</p>

<div class="row">
    <div class="col-md-8">
        <div class="box">
            <div class="box-header"></div>
            <div class="box-body">
                <h1><?php echo $this->titre?></h1>
                <form role="form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">File input</label>
                            <input type="file" id="exampleInputFile">

                            <p class="help-block">Example block-level help text here.</p>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Check me out
                            </label>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
