<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<button type="button" class="btn btn-warning" onclick="AjaxLoader('<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action'=>'showdetailsmoduls'))?>','0','moduledesc');">Annuler</button>

<div class="box box-success">
    <div class="box-header with-border">

    </div>
    <div class="box-body">
        <form class="form-horizontal" role="form" action="" method="post">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label"><?=$this->translate('UeAdd_El_TItre')?></label>

                <div class="col-sm-10">
                    <input type="email" class="form-control" id="" placeholder="Email">
                </div>
            </div>
        </form>
    </div>
</div>