<button type="button" class="btn btn-warning" onclick="AjaxLoader('<?=$this->url('pedagogie/controller-action',array('controller'=>'calendrier','action'=>'caldetailglob'))?>','0','moduledesc');">Annuler</button>

<div class="box box-success">
    <div class="box-header with-border">

    </div>
    <div class="box-body">
        <form class="form-horizontal" role="form" action="" method="post">

            <div class="form-group">
                <label for="typeactivite" class="col-sm-2 control-label"><?=$this->translate('Type_Activite')?></label>

                <div class="col-sm-10">
                    <select id="typeactivite" name="typeactivite" class="form-control" >
                        <option value="">Selectionnée type d'activé</option>
                        <optgroup label="Presentiel">
                            <option value="Regroupementenseignement">Regroupement d'enseignement</option>
                            <option value="demarageperiode">Demarage de la période</option>
                            <option value="seminaire">Séminaire</option>
                        </optgroup>
                        <optgroup label="E-learning">
                            <option value="Chat">Chat</option>
                            <option value="Forum">Forum</option>
                            <option value="Forum">Ouverture de cours sur la plateforme</option>
                        </optgroup>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="modules" class="col-sm-2 control-label"><?=$this->translate('Titre_event')?></label>

                <div class="col-sm-10">
                        <input type="text" name="titreevenement" id="titreevenement">
                </div>
            </div>
            <div class="form-group">
                <label for="modules" class="col-sm-2 control-label"><?=$this->translate('Select_Modules')?></label>

                <div class="col-sm-10">
                    <select id="modules" name="modules" class="form-control" >
                        <option value="">Selectionnée un module</option>
                            <option value="Math">Math 1</option>
                            <option value="E-com">E-com</option>
                            <option value="Comptabilité">Comptabilité</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="PlanCours" class="col-sm-2 control-label"><?=$this->translate('Plan_Cours')?></label>

                <div class="col-sm-10">
                    <select id="PlanCours" name="PlanCours" class="form-control" >
                        <option value="">Selectionnée Un chapitre</option>
                        <option value="ch1">Chapitre 1</option>
                        <option value="ch2">Chapitre 2</option>
                        <option value="ch3">Chapitre 3</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="date" class="col-sm-2 control-label"><?=$this->translate('date')?></label>

                <div class="col-sm-5">
                    de <input data-provide="datepicker" type="date" class="form-control" name="date_debut" placeholder="<?=$this->translate('date_debut')?>">
                </div>
                <div class="col-sm-5">
                    à <input  data-provide="datepicker" type="date" class="form-control" name="date_fin"  placeholder="<?=$this->translate('date_fin')?>">
                </div>
            </div>

            <div class="form-group">
                <label for="date" class="col-sm-2 control-label"><?=$this->translate('heur')?></label>

                <div class="col-sm-5">
                    de <input type="time" class="form-control" name="heur_debut"  placeholder="<?=$this->translate('heur_debut')?>">
                </div>
                <div class="col-sm-5">
                    à <input type="time" class="form-control" name="heur_fin" placeholder="<?=$this->translate('heur_fin')?>">
                </div>
            </div>





            <div class="form-group">
                <label for="description" class="col-sm-2 control-label"><?=$this->translate('description')?></label>

                <div class="col-sm-10">
                    <textarea name="description"placeholder="<?=$this->translate('description')?>" cols="150" rows="5">
                    </textarea>
                </div>

            </div>
        </form>
    </div>
</div>