<div class="col-md-12">
    <div class="box box-solid">
        <div class="box-header with-border">
            <h3>Details de l'habilitation de l'ECUE</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="box-group" id="accordion">
                <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                <div class="panel box box-primary">
                    <div class="box-header with-border">
                        <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseEns" aria-expanded="false" class="collapsed">
                                Enseignement
                            </a>
                        </h4>
                    </div>
                    <div id="collapseEns" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                        <div class="box-body">

                        </div>
                    </div>
                </div>


                <div class="panel box box-danger">
                    <div class="box-header with-border">
                        <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseAP" class="collapsed" aria-expanded="false">
                                Activité pratique
                            </a>
                        </h4>
                    </div>
                    <div id="collapseAP" class="panel-collapse collapse" aria-expanded="false">
                        <div class="box-body">

                        </div>
                    </div>
                </div>

                <div class="panel box box-primary">
                    <div class="box-header with-border">
                        <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseVUE" aria-expanded="false" class="collapsed">
                                Validation de l'ECUE
                            </a>
                        </h4>
                    </div>
                    <div id="collapseVUE" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                        <div class="box-body">

                        </div>
                    </div>
                </div>

                <div class="panel box box-danger">
                    <div class="box-header with-border">
                        <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapsePR" class="collapsed" aria-expanded="false">
                                Prèrequit
                            </a>
                        </h4>
                    </div>
                    <div id="collapsePR" class="panel-collapse collapse" aria-expanded="false">
                        <div class="box-body">

                        </div>
                    </div>
                </div>

                <div class="panel box box-primary">
                    <div class="box-header with-border">
                        <h4 class="box-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapsePC" aria-expanded="false" class="collapsed">
                                Plan de cours
                            </a>
                        </h4>
                    </div>
                    <div id="collapsePC" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                        <div class="box-body">

                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>