<div class="nav-tabs-custom">
    <ul class="nav nav-tabs pull-left">
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Enseignement</a></li>
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Activité protique</a></li>
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Validation de l'UE</a></li>
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Prérequit</a></li>
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Plan de cours</a></li>
        <li class="active"><a href="#tab_1-1" data-toggle="tab">Référentiel de compétence</a></li>
        <!--li class="pull-left header"><i class="fa fa-th"></i> Habilitation présentiel</--li-->
    </ul>

</div>