<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<div class="box">
    <div class="box-header">
      <h3><?=$this->translate("update_ue")?></h3>
    </div>
    <div class="box-body">
        <form class="form-horizontal" role="form" action="" method="post">
            <div class="form-group">
                <label for="code" class="col-sm-2 control-label"><?=$this->translate("update_ue_code")?></label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="code" placeholder="<?=$this->translate("update_ue_code")?>">
                </div>
            </div>
            <div class="form-group">
                <label for="labelle" class="col-sm-2 control-label"><?=$this->translate("update_ue_labelle")?></label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="labelle" placeholder="<?=$this->translate("update_ue_labelle")?>">
                </div>
            </div>
            <div class="form-group">
                <label for="credit" class="col-sm-2 control-label"><?=$this->translate("update_ue_cr")?></label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="credit" placeholder="<?=$this->translate("update_ue_cr")?>">
                </div>
            </div>

            <div class="form-group">
                <label for="coef" class="col-sm-2 control-label"><?=$this->translate("update_ue_coef")?></label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="coef" placeholder="<?=$this->translate("update_ue_coef")?>">
                </div>
            </div>
            <div class="form-group">
                <label for="rg" class="col-sm-2 control-label"><?=$this->translate("update_ue_rg")?></label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" id="rg" placeholder="<?=$this->translate("update_ue_rg")?>">
                </div>
            </div>

<div class="center-block">
<input type="submit" class="btn btn-success"value="Enregistrer"> </div>
        </form>

    </div>
</div>