<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<!--debut UE Objectifs de l’UE -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('ECUE_ENSEIGEMENT')?></h3>
            </div>
            <div class="box-body">
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-aqua-gradient">
                        <th>Cours</th>
                        <th>TD</th>
                        <th>TP</th>
                        <th>CI</th>
                    </tr>
                    </thead>

                    <tbody>
                    <th>
                        <table class="table table-bordered">
                            <tr>
                                <th class="bg-fuchsia">Forum</th>
                                <td>5</td>
                            </tr>
                            <tr>
                                <th class="bg-fuchsia">Chat</th>
                                <td>3</td>
                            </tr>
                            <tr>
                                <th class="bg-fuchsia">Regrouppement</th>
                                <td>2</td>
                            </tr>
                        </table>
                    </th>
                    <th>
                        <table class="table table-bordered">
                            <tr>
                                <th class="bg-fuchsia">T.A.F</th>
                                <td>5</td>
                            </tr>

                        </table>
                    </th>
                    <th>TP</th>
                    <th>CI</th>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--fin UE Objectifs de l’UE -->