<!--debut UE Objectifs de l’UE -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('Objectifs_UE')?></h3>
            </div>
            <div class="box-body"></div>
        </div>
    </div>
</div>
<!--fin UE Objectifs de l’UE -->


<!--debut UE Pré-requis  -->
<div class="row">
    <div class="col-md-7">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('')?></h3>
            </div>
            <div class="box-body"></div>
        </div>
    </div>
</div>

<!--fin UE Pré-requis  -->


<!--debut UE Pré-requis  -->
<div class="row">
    <div class="col-md-7">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('')?></h3>
            </div>
            <div class="box-body"></div>
        </div>
    </div>
</div>

<!--fin UE Pré-requis  -->