<!--debut UE Objectifs de l’UE -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('Objectifs_UE')?></h3>
            </div>
            <div class="box-body">
                <ul>
               <li>Etre capable de mettre en pratique toutes les connaissances et compétences acquises dans l'UE pour le développement de sites Web dynamiques.</li>
               <li>Etre capable de réaliser un site Web dynamique respectant les normes du W3C</li>
                <li>Apprendre les technologies XML afin de structurer les données</li>
                <li>Lecture de comportement des utilisateurs afin de proposer une solution plus appropriée</li>
                <li>Etre capable d’évaluer un site web dynamique</li>
                </ul>


            </div>
        </div>
    </div>
</div>
<!--fin UE Objectifs de l’UE -->


<!--debut UE Pré-requis  -->
<div class="row">
    <div class="col-md-7">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('prerequis_ue')?></h3>
            </div>
            <div class="box-body">
               <ul>
               <li>Connaissances en développement Web (HTML, CSS, JavaScipt)</li>
               <li>Connaissances en architecture logiciel et modélisation UML</li>
               <li>Connaissances en bases de données</li>




               </ul>


            </div>
        </div>
    </div>
</div>

<!--fin UE Pré-requis  -->


<!--debut UE Pré-requis  -->
<div class="row">
    <div class="col-md-7">
        <div class="box">
            <div class="box-header">
                <h3><?=$this->translate('elelement_ue')?></h3>
            </div>
            <div class="box-body">
                <h3>3.1- Enseignements </h3>
                <table class="table table-bordered">
                    <thead>
                    <tr class="bg-green-gradient">
                       <th>Eléments constitutifs</th>
                       <th>Volume des heures de formation présentielles<small>(14 semaines</small></th>
                       <th>Crédits</th>
                       </tr>
                     </thead>
                    <tbody>
                    <!--ECUE-->
                    <tr>

                        <th></th>
                        <th>Cours</th>
                        <th>TD</th>
                        <th>TP</th>
                        <th>CI</th>
                        </tr>
<tr>
    <td>Ergonomie des sites Web</td>
    <td>Technologies XML</td>
    <td>- Cyber sécurité</td>



</tr></tbody></table>


            </div>
        </div>
    </div>
</div>

<!--fin UE Pré-requis  -->