<?php

// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<?=$this->translate('application_navigation_home')?>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($annees as $annee) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($annee->idanneeuniv);?></td>
            <td><?php echo $this->escapeHtml($annee->labelanneeuniv);?></td>

        </tr>
    <?php endforeach; ?>
</table>