<?php
declare(strict_types = 1);
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<script type="text/javascript">
    $(document).ready(function () {
        AjaxLoader('<?=$this->url('pedagogie/controller-action',array('controller'=>'dashboard','action' =>'infogenform'), null, true); ?>','0','dashboard');
    });
</script>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3>Information générale</h3>
            </div>
            <div class="box-body" id="dashboard">
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
<h3>Listes des formations</h3>
            </div>
            <div class="box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Foramtion</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>LAM</td>
                        <td>
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>Type Diplôme</th>
                                    <td>Licence Appliquée</td>
                                </tr>
                                <tr>
                                    <th>Domaine</th>
                                    <td>Sciences économiques et de gestion</td>
                                </tr>
                                <tr>
                                    <th>Mention</th>
                                    <td>Management</td>
                                </tr>
                                <tr>
                                    <th>Spécialité</th>
                                    <td>gestion des petites et moyennes entreprises</td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                        <td>
                            <a href="<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action' =>'showdetailsformation'), null, true); ?>" class="btn btn-info"><i class="fa fa-eye"></i> </a>
                            <a href="#" class="btn btn-success"><i class="fa fa-edit"></i> </a>
                            <a href="#" class="btn btn-danger"><i class="fa fa-trash"></i> </a>

                        </td>
                    </tr>
                    </tbody>
                </table>

               <div class="box-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Foramtion</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>MPSQ</td>
                            <td>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th>Type Diplôme</th>
                                        <td>Licence Appliquée</td>
                                    </tr>
                                    <tr>
                                        <th>Domaine</th>
                                        <td>Sciences économiques et de gestion</td>
                                    </tr>
                                    <tr>
                                        <th>Mention</th>
                                        <td>Administration des affaires</td>
                                    </tr>
                                    <tr>
                                        <th>Spécialité</th>
                                        <td>Gestion de la PME</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td>
                                <a href="<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action' =>'showdetailsformation'), null, true); ?>" class="btn btn-info"><i class="fa fa-eye"></i> </a>
                                <a href="#" class="btn btn-success"><i class="fa fa-edit"></i> </a>
                                <a href="#" class="btn btn-danger"><i class="fa fa-trash"></i> </a>

                            </td>
                        </tr>
                        </tbody>
                    </table>

                   <div class="box-body">
                       <table class="table table-hover">
                           <thead>
                           <tr>
                               <th>Foramtion</th>
                               <th>Description</th>
                               <th>Action</th>
                           </tr>
                           </thead>
                           <tbody>
                           <tr>
                               <td>LASTIC</td>
                               <td>
                                   <table class="table">
                                       <tbody>
                                       <tr>
                                           <th>Type Diplôme</th>
                                           <td>Master</td>
                                       </tr>
                                       <tr>
                                           <th>Domaine</th>
                                           <td>technologies des télécommunications</td>
                                       </tr>
                                       <tr>
                                           <th>Mention</th>
                                           <td>les réseaux téléinformatiques</td>
                                       </tr>
                                       <tr>
                                           <th>Spécialité</th>
                                           <td>Gestion de la PME</td>
                                       </tr>
                                       </tbody>
                                   </table>
                               </td>
                               <td>
                                   <a href="<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action' =>'showdetailsformation'), null, true); ?>" class="btn btn-info"><i class="fa fa-eye"></i> </a>
                                   <a href="#" class="btn btn-success"><i class="fa fa-edit"></i> </a>
                                   <a href="#" class="btn btn-danger"><i class="fa fa-trash"></i> </a>

                               </td>
                           </tr>
                           </tbody>
                       </table>

            </div>

        </div>


    </div>
</div>
<pre>
    <?php print_r($formations)?>
</pre>
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-body">
            <?php foreach ($listeformation as $formation):?>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><?=$formation->labeltype?> : <?=$formation->Label?></th>
                        </tr>
                    </thead>
                </table>
            <?php endforeach;?>
        </div>


    </div>
</div>


</div>
