<?php
declare(strict_types = 1);
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<script type="text/javascript">
    $(document).ready(function () {
        AjaxLoader('<?=$this->url('pedagogie/controller-action',array('controller'=>'dashboard','action' =>'infogenform'), null, true); ?>','0','dashboard');
    });
</script>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3>Information générale</h3>
            </div>
            <div class="box-body" id="dashboard">
            </div>
        </div>
    </div>
</div>



<!--pre>
    <?php //print_r($formations)?>
</pre-->
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-body">
            <div class="box-header">
                <h3>Listes des formations</h3>
            </div>
            <?php foreach ($this->formations as $key => $formation):?>
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr class="bg-blue">
                            <th colspan="4" style="text-align: center;"><?=$key?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($formation as $keyParcours => $Parcours):?>
                            <tr>
                                <td class="col-md-3"><?=$Parcours['tooltip']?> <?=$Parcours['title']?></td>
                                <td class="col-md-7">
                                    <!--Table descriptif de la formation-->
                                    <table class="table bg-light-blue">
                                        <?php foreach ($Parcours['description'] as $keydesc => $desc):?>
                                            <tr>
                                                <td class="col-md-4"><?=$desc['type']?></td>
                                                <td class="col-md-8"><?=$desc['label']?></td>
                                            </tr>
                                        <?php endforeach;?>
                                    </table>
                                </td>
                                <td class="col-md-2">
                                    <a href="<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action' =>'showdetailsformation','id'=>$Parcours['key']), null, true); ?>" class="btn btn-info"><i class="fa fa-eye"></i> </a>
                                    <a href="#" class="btn btn-success"><i class="fa fa-edit"></i> </a>
                                    <a href="#" class="btn btn-danger"><i class="fa fa-trash"></i> </a>
                                    <a href="<?=$this->url('enseignant/controller-action',array('controller'=>'create','action' =>'inviter-coordinateur','id'=>$Parcours['key']), null, true); ?>" class="btn btn-info"><i class="fa fa-user-circle"></i> </a>

                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>

                </table>
            <?php endforeach;?>
        </div>


    </div>
</div>


</div>
