<?php
declare(strict_types = 1);
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */

//echo "<pre>";print_r($this->modules); echo "</pre>";
?>

<script type="text/javascript">
    function getAddUe(idsemestre,idformation){
        AjaxLoaderMultiParam("<?=$this->url('pedagogie/controller-action',array('controller'=>'create','action'=>'createue'))?>",{sem:'<?=$this->sem?>',idform:<?=$this->idform?>},'moduledesc');
    }

    function getGestCalendrier(idsemestre,idformation){
        AjaxLoader("<?=$this->url('pedagogie/controller-action',array('controller'=>'create','action'=>'createue'))?>","0",'moduledesc');
    }
</script>
<?php if($this->ecran!='visualisation'):?>
<button type="button" class="btn btn-info pull-right"  onclick="getAddUe();"><i class="fa fa-edit"></i> <?=$this->translate('DetailModule_Btn_AjoutModule')?></button>
<?php endif;?>
<?php if(!$this->ecran):?>
<a href="<?=$this->url('pedagogie/controller-action',array('controller'=>'moduleens','action'=>'gestionunite','id'=>$this->Niveau->idniveauformation))?>"  class="btn btn-info pull-left" ><i class="fa fa-edit"></i> <?=$this->translate('DetailModule_Btn_ModifierdetailModule')?></a>
<?php endif;?>
<br>
<hr>
 <table class="table table-bordered">

    <tbody>

        <?php foreach ($this->modules as $p):?>
            <tr class="bg-purple-gradient text-center">

                <th>Code_Ue</th>
                <th>Libelle</th>
                <th>Cr</th>
                <th>Coef</th>
                <th>Nat</th>
                <th>Rg</th>

                <th>Action</th>
                <th>Eléments d'enseignements</th>
            </tr>
        <tr>
            <td colspan="8" class="bg-gray">Niveau <?=$p['level']?> : <?=$p['periode']?></td>
        </tr>
        <?php foreach ($p['UE'] as $keyue=> $module):?>


                <tr>
        <!--UE-->
        <td><?=$module['info']['codeue']?> (<?=$module['info']['codemes']?>)</td>
        <td><?=$module['info']['titremodule']?></td>
        <td><?=$module['info']['credit']?></td>
        <td><?=$module['info']['coefficient']?></td>
        <td><?=$module['info']['idNature']?></td>
        <td><?=$module['info']['idRegime']?></td>

        <td>
            <!--Debut action menu-->
            <div class="btn-group">
                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Liste</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <?php if($this->ecran!='visualisation'):?>
                    <li><a onclick="showinmodal('<?=$this->url('pedagogie/controller-action',array('controller'=>'create','action'=>'createue'))?>',{id:<?=$keyue?>,Type:'UE',sem:'<?=$this->sem?>',idform:<?=$this->idform?>});"><i class="fa fa-edit"></i> Modifier</a></li>
                    <li><a onclick="showinmodal('<?=$this->url('pedagogie/controller-action',array('controller'=>'create','action'=>'createue'))?>',{idue:<?=$keyue?>,Type:'UE',sem:'<?=$this->sem?>',idform:<?=$this->idform?>});"><i class="fa fa-edit"></i> Ajouter ECUE</a></li>
                    <li class="divider"></li>
                    <?php endif;?>
                    <li><a href="#"><i class="fa fa-eye"></i>Details</a></li>

                    <li><a href="#">Details e-learning</a></li>

                    <li><a href="#">Details présentielle</a></li>
                </ul>
            </div>
            <!---->
        </td>
        <!--FIN UE-->
        <!--ECUE-->
        <td>
            <table class="table table-bordered">
                <thead>
                <!--ECUE-->
                <tr class="bg-green-gradient">

                    <th>Code_ECUE</th>
                    <th>Libelle</th>
                    <th>Cr</th>
                    <th>Coef</th>
                    <th>Rg</th>
                    <th>Action</th>
                </tr>
                <!--FIN ECUE-->
                </thead>
                <tbody>
                <!--ECUE-->
                <!--FIN ECUE-->
                <?php if (isset($module['ECUE'])):?>
                <?php foreach ($module['ECUE'] as $keyecue => $ecue):?>
                <!--ECUE-->
                <tr>

                    <td><?=$ecue['codeue']?>(<?=$ecue['codemes']?>)</td>
                    <td><?=$ecue['titremodule']?></td>
                    <td><?=$ecue['credit']?></td>
                    <td><?=$ecue['coefficient']?></td>
                     <td><?=$ecue['idRegime']?></td>
                    <td>
                        <!--Debut action menu-->
                        <div class="btn-group">
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Liste</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                        <?php if($this->ecran!='visualisation'):?>
                                <li><a onclick="showinmodal('<?=$this->url('pedagogie/controller-action',array('controller'=>'create','action'=>'createue'))?>',{id:<?=$keyecue?>,Type:'ECUE',sem:'<?=$this->sem?>',idform:<?=$this->idform?>});"><i class="fa fa-edit"></i> Modifier</a></li>
                            <?php endif;?>
                            <li class="divider"></li>

                                <li><a href="#" onclick="showinmodal('<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action'=>'detailmodulepresence'))?>',{id:2,Type:'ECUE'});"><i class="fa fa-eye"></i>Details</a></li>
                                 <li><a href="#" onclick="showinmodal('<?=$this->url('pedagogie/controller-action',array('controller'=>'show','action'=>'detailmodulevirtual'))?>',{id:2,Type:'ECUE'});">Details e-learning</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Details présentielle</a></li>
                            </ul>
                        </div>

                        <!---->

                    </td>
                </tr>
                <!--FIN ECUE-->
                <?php endforeach;?>
<?php endif;?>
                </tbody>
            </table>
        </td>

        <!--FIN ECUE-->
    </tr>
    <?php endforeach;?>
    <?php endforeach;?>
    </tbody>
 </table>