<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */

?>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_v" data-toggle="tab" aria-expanded="true"><?=$this->translate('ens_v_modules')?></a></li>
        <li><a href="#tab_p" data-toggle="tab" aria-expanded="true"><?=$this->translate('ens_p_modules')?></a></li>

    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="tab_v">
            je suis tab v
            </div>
        <div class="tab-pane" id="tab_p">
            je suis tab p
        </div>
    </div>
</div>
