<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<div class="box">

    <div class="box-header">
        <h1><i class="fa fa-university"></i> <?=$this->translate('ideeeprojet_titre_principal')?></h1>

    </div>
    <div class="box-body">
        <a href="#" class="btn btn-danger"><i class="fa fa-trash"></i></a>
        <h2>Ideeprojet Module</h2>
        <h3>Formations Controller</h3>
        <h4>Show Action</h4>
    </div>
</div>

