<?php
/**
 * ZF2 Application built by ZF2rapid
 *
 * @copyright (c) 2015 John Doe
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */


?>
<div class="row">
    <div class="col-ms-12">
        <div class="box">
            <div class="box-header">

            </div>
            <div class="box-body">
                <table class="table table-bordered">
                    <thead>
                        <th>Model de composant principale de Formation</th>
                        <th>Model de composition de formation</th>
                    </thead>
                    <tbody>
                        <td></td>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>